# Generated by Django 4.0.6 on 2022-07-21 02:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_employee_email_alter_employee_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='age',
        ),
        migrations.AddField(
            model_name='employee',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2022, 7, 21, 2, 54, 34, 755052, tzinfo=utc)),
        ),
    ]
