# Generated by Django 4.0.6 on 2022-07-21 02:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_employee_age_employee_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2022, 7, 21, 2, 56, 6, 966056, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='city',
            field=models.IntegerField(choices=[(29, 'Ha Noi'), (90, 'Ha Nam')], default='Choose', max_length=20),
        ),
    ]
