# Generated by Django 4.0.6 on 2022-07-21 02:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_employee_birthday_alter_employee_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2022, 7, 21, 2, 57, 1, 12032, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='city',
            field=models.IntegerField(choices=[(0, 'Choose'), (29, 'Ha Noi'), (90, 'Ha Nam')], default=0),
        ),
    ]
